-- specs/015-contact-us-page. Adds one nullable column to the existing
-- `companies` table (owned by 001) plus one new, additive RLS policy that
-- lets any tenant role read their own company's row (previously only
-- system_admin/auth_service could read `companies` at all, via
-- `companies_system_admin_only`). See data-model.md §1-2 and research.md §3.
--
-- Hand-written in full (not `prisma migrate dev --create-only` output) —
-- no live database is reachable from this environment. The ALTER TABLE
-- below is exactly what Prisma would have generated from the schema.prisma
-- diff; everything below the "HAND-ADDED" marker is, as always
-- (coding_standard.md §4.2), not expressible in schema.prisma at all.

-- AlterTable
ALTER TABLE "companies" ADD COLUMN "operating_hours" TEXT;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`.
-- ============================================================================

-- research.md §3: additive SELECT-only policy. `companies_system_admin_only`
-- (FOR ALL) already covers every write path and every system_admin/
-- auth_service read; Postgres OR's multiple permissive policies together per
-- command, so this only ever *adds* a read path for a caller's own row — it
-- can never widen INSERT/UPDATE/DELETE, which remain gated solely by the
-- existing FOR ALL policy.
CREATE POLICY "companies_tenant_self_read" ON "companies"
  FOR SELECT
  USING ("id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid);
