-- specs/006-student-browse-cart-checkout fully migrates `orders`, completing
-- the dependency contract specs/005 declared without owning (research.md §7).
-- This is an ADDITIVE migration on top of 20260906180000_orders_deliveries_audit
-- (coding_standard.md §4.2 — never edit a prior migration).

-- AlterTable
ALTER TABLE "orders"
  ADD COLUMN "fulfilment_type" TEXT NOT NULL DEFAULT 'pickup',
  ADD COLUMN "payment_status" TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN "payment_gateway_ref" TEXT,
  ADD COLUMN "created_by" UUID,
  ADD COLUMN "updated_by" UUID;

-- `otp` was created NOT NULL in 005's migration (which never actually
-- created a row through the app — that only started with this feature).
-- data-model.md §1: nullable, generated once at payment_pending -> order_placed.
ALTER TABLE "orders" ALTER COLUMN "otp" DROP NOT NULL;

-- 005's migration defaulted status to 'order_placed' as a placeholder
-- (before this feature existed to define the real lifecycle). The real
-- default is 'payment_pending' — every order starts unpaid.
ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'payment_pending';

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. data-model.md's own CHECK constraints, the FR-016
-- one-unresolved-order-per-student index, and the role-conditional RLS
-- policies that replace 005's single interim blanket policy.
-- ============================================================================

ALTER TABLE "orders" ADD CONSTRAINT "orders_total_amount_positive" CHECK ("total_amount" > 0);
ALTER TABLE "orders" ADD CONSTRAINT "orders_fulfilment_type_pickup" CHECK ("fulfilment_type" = 'pickup');

-- FR-016/research.md §3: a student may have at most one unresolved
-- (payment_pending or payment_failed) order at a time, enforced at the DB
-- layer, not just by the API checking first.
CREATE UNIQUE INDEX "orders_one_unresolved_per_user" ON "orders" ("user_id")
  WHERE "status" IN ('payment_pending', 'payment_failed');

-- --- Row Level Security ------------------------------------------------------
-- Replaces 005's interim `orders_tenant_isolation` (a single blanket
-- company-scoped policy) with data-model.md's role-conditional design:
-- Students only ever see/create their own rows; Staff/Company Admin see
-- every order in their company (005's own "Incoming Orders" need); only the
-- payment webhook and Staff's one delivered-transition may UPDATE. No
-- system_admin bypass anywhere (research.md §6).
DROP POLICY "orders_tenant_isolation" ON "orders";

CREATE POLICY "student_own_orders" ON "orders"
  FOR SELECT
  USING (
    current_setting('app.current_role', true) = 'student'
    AND "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    AND "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
  );

CREATE POLICY "student_create_own_orders" ON "orders"
  FOR INSERT
  WITH CHECK (
    current_setting('app.current_role', true) = 'student'
    AND "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    AND "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
  );

CREATE POLICY "staff_company_orders" ON "orders"
  FOR SELECT
  USING (
    current_setting('app.current_role', true) IN ('staff', 'company_admin')
    AND "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
  );

-- 005's own order_placed -> delivered transition. RLS is a backstop here
-- (defense-in-depth) — the API layer is what actually restricts which
-- columns/transition Staff may perform (coding_standard.md §4.3).
CREATE POLICY "staff_deliver_own_company_orders" ON "orders"
  FOR UPDATE
  USING (
    current_setting('app.current_role', true) = 'staff'
    AND "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
  )
  WITH CHECK (
    current_setting('app.current_role', true) = 'staff'
    AND "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
  );

-- The payment webhook has no user session at all (server-to-server,
-- signature-verified, research.md §4) — it runs under a dedicated trusted
-- system-actor identity, the same narrowly-scoped pattern already
-- established for `auth_service` (specs/002/003/009) and `auth_service`'s
-- own pre-auth lookups, applied here under its own name so a reviewer can
-- immediately tell which code path this bypass belongs to. A single FOR ALL
-- policy (not per-command) since the webhook only ever does one thing:
-- look a row up by payment_gateway_ref and transition it.
CREATE POLICY "payment_service_orders" ON "orders"
  FOR ALL
  USING (current_setting('app.current_system_actor', true) = 'payment_service')
  WITH CHECK (current_setting('app.current_system_actor', true) = 'payment_service');
