-- AlterTable
ALTER TABLE "users" ADD COLUMN     "reset_password_otp" TEXT,
ADD COLUMN     "reset_password_otp_expires_at" TIMESTAMPTZ(6),
ADD COLUMN     "reset_password_otp_attempts" INTEGER NOT NULL DEFAULT 0;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. specs/003-forgot-password-otp-reset's data-model.md
-- §1 requires no new RLS policy: 001's existing `users_tenant_isolation`
-- policy (as widened by 002's own migration for the pre-auth auth_service
-- bypass) is predicated on `company_id`/role only, not on individual column
-- names, so it already scopes these 3 new columns identically to every
-- other `users` column. No GRANT change either — app_user already has
-- SELECT/UPDATE on `users` from 001's migration, and these columns are
-- read/written through that same grant.
-- ============================================================================
