-- Reverses part of 20260911180542_msg91_sms_otp_mobile_verification: on
-- clarification, only registration-time mobile verification uses SMS
-- (MSG91) — password-reset and order-pickup OTPs stay on FCM push, so
-- device_registrations is restored exactly as it was
-- (20260906170000_device_registrations/migration.sql — same DDL/RLS/grant,
-- copied verbatim so this stays a real, auditable migration rather than a
-- silent hand-edit of an already-applied one). mobile_verifications
-- (registration-only) is unaffected and stays.
--
-- Also drops users.reset_password_otp_last_sent_at, added by the same prior
-- migration for a resend-cooldown that only made sense while password-reset
-- was SMS-billed — now that it's back on free FCM push, that cooldown
-- doesn't apply to it (the mobile-verification send endpoint keeps its own
-- cooldown via mobile_verifications.last_sent_at, unaffected).

-- CreateTable
CREATE TABLE "device_registrations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "fcm_token" TEXT NOT NULL,
    "refresh_token_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "device_registrations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "device_registrations_fcm_token_key" ON "device_registrations" ("fcm_token");

-- AddForeignKey
ALTER TABLE "device_registrations" ADD CONSTRAINT "device_registrations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "device_registrations" ADD CONSTRAINT "device_registrations_refresh_token_id_fkey" FOREIGN KEY ("refresh_token_id") REFERENCES "refresh_tokens"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AlterTable
ALTER TABLE "users" DROP COLUMN "reset_password_otp_last_sent_at";

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. Copied verbatim from
-- 20260906170000_device_registrations/migration.sql's own hand-added
-- section.
-- ============================================================================

CREATE INDEX "device_registrations_user_id_idx" ON "device_registrations" ("user_id");

GRANT SELECT, INSERT, UPDATE, DELETE ON "device_registrations" TO app_user;

ALTER TABLE "device_registrations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "device_registrations_self_or_system" ON "device_registrations"
  FOR ALL
  USING (
    "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  )
  WITH CHECK (
    "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  );
