-- specs/010-resume-pending-order-payment. Fixes a real correctness bug in
-- 006's original design (research.md §1): a single, overwritable
-- orders.payment_gateway_ref column meant a late-arriving webhook
-- confirmation for a superseded attempt would find no matching order at
-- all, silently dropping a payment the student actually completed.

-- CreateTable
CREATE TABLE "payment_attempts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "order_id" UUID NOT NULL,
    "gateway_ref" TEXT NOT NULL,
    "is_current" BOOLEAN NOT NULL DEFAULT true,
    "outcome" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolved_at" TIMESTAMPTZ(6),

    CONSTRAINT "payment_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "payment_attempts_gateway_ref_key" ON "payment_attempts" ("gateway_ref");

-- AddForeignKey
ALTER TABLE "payment_attempts" ADD CONSTRAINT "payment_attempts_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`.
-- ============================================================================

-- FR-006/research.md §2: exactly one current attempt per order, enforced at
-- the DB layer, not just application logic.
CREATE UNIQUE INDEX "payment_attempts_one_current_per_order" ON "payment_attempts" ("order_id") WHERE "is_current" = true;

-- The webhook's hot lookup path.
CREATE INDEX "payment_attempts_order_id_idx" ON "payment_attempts" ("order_id");

-- --- Non-superuser application role grant ------------------------------------
-- No DELETE — an attempt row is never removed, only superseded (is_current)
-- or resolved (outcome/resolved_at).
GRANT SELECT, INSERT, UPDATE ON "payment_attempts" TO app_user;

-- --- Row Level Security ------------------------------------------------------
-- data-model.md's own instruction: scoped identically to `orders` (joined
-- via order_id), no system_admin bypass. Three policies, mirroring the
-- shape already established on `orders` itself (migration 20260906190000):
-- general read for the order's own student/staff/company_admin, a
-- student-scoped write policy for the retry-payment endpoint's own writes
-- (creating a new attempt, marking prior ones non-current — it runs under
-- the real student's own context, not a bypass), and the same
-- `payment_service` system-actor policy the webhook already uses on `orders`,
-- for its own lookup/outcome-write.
ALTER TABLE "payment_attempts" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "payment_attempts_select" ON "payment_attempts"
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM "orders" o
      WHERE o."id" = "payment_attempts"."order_id"
        AND (
          (current_setting('app.current_role', true) = 'student'
           AND o."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid)
          OR (current_setting('app.current_role', true) IN ('staff', 'company_admin')
              AND o."company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid)
        )
    )
  );

CREATE POLICY "payment_attempts_student_write" ON "payment_attempts"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "orders" o
      WHERE o."id" = "payment_attempts"."order_id"
        AND current_setting('app.current_role', true) = 'student'
        AND o."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "orders" o
      WHERE o."id" = "payment_attempts"."order_id"
        AND current_setting('app.current_role', true) = 'student'
        AND o."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    )
  );

CREATE POLICY "payment_service_payment_attempts" ON "payment_attempts"
  FOR ALL
  USING (current_setting('app.current_system_actor', true) = 'payment_service')
  WITH CHECK (current_setting('app.current_system_actor', true) = 'payment_service');
