-- CreateTable
CREATE TABLE "device_registrations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "fcm_token" TEXT NOT NULL,
    "refresh_token_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "device_registrations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "device_registrations_fcm_token_key" ON "device_registrations" ("fcm_token");

-- AddForeignKey
ALTER TABLE "device_registrations" ADD CONSTRAINT "device_registrations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "device_registrations" ADD CONSTRAINT "device_registrations_refresh_token_id_fkey" FOREIGN KEY ("refresh_token_id") REFERENCES "refresh_tokens"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. Built as the minimal slice of
-- specs/009-order-fcm-push-notifications this feature (003's forgot-password
-- FCM delivery) actually needs — see the model's own doc-comment in
-- schema.prisma for what's deliberately NOT built yet (the authenticated
-- POST /me/devices endpoint, the order-webhook notification hook, and
-- order_audit_logs event logging — all tied to tables/flows that don't
-- exist in this codebase yet).
-- ============================================================================

-- The hot lookup path for "which devices does this user have registered" —
-- both the unauthenticated upsert (research.md §7) and every FCM send.
CREATE INDEX "device_registrations_user_id_idx" ON "device_registrations" ("user_id");

-- --- Non-superuser application role grant ------------------------------------
-- DELETE is granted for future session-ending cascade cleanup (data-model.md's
-- own "Cascading deletes" section — not fully wired in this pass beyond what
-- 003's forgot-password flow itself needed).
GRANT SELECT, INSERT, UPDATE, DELETE ON "device_registrations" TO app_user;

-- --- Row Level Security ------------------------------------------------------
-- data-model.md §1: self-scoped by user_id, no system_admin bypass. A THIRD
-- disjunct, app.current_system_actor = 'auth_service', is added here (beyond
-- what data-model.md's own prose describes) for two call sites this feature
-- actually has: DevicesService.upsertUnauthenticated (research.md §7 — no
-- session/user context exists yet at that point in the forgot-password flow)
-- and the FCM adapter's own token lookup at send time (same trusted
-- service-role reasoning, since sending a notification is a system-triggered
-- side effect, not a user's own request). Mirrors the identical auth_service
-- pattern already established on users/roles/auth_audit_logs.
ALTER TABLE "device_registrations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "device_registrations_self_or_system" ON "device_registrations"
  FOR ALL
  USING (
    "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  )
  WITH CHECK (
    "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  );
