-- specs/014-msg91-sms-otp-mobile-verification. Three things:
-- 1. A resend-cooldown timestamp on users (password-reset OTP now costs a
--    real, billed SMS send, unlike the FCM push it replaces).
-- 2. Drops device_registrations entirely — its only substantive column was
--    fcm_token @unique, and FCM is removed from the platform entirely.
--    Dropping the table cascades its RLS policies automatically; no
--    explicit DROP POLICY needed.
-- 3. A new mobile_verifications table for registration-time mobile-number
--    verification (pre-account — no User row exists yet at verification
--    time, so this can't reuse users.reset_password_otp*'s columns).
--
-- Generated via `prisma migrate diff` against the live DB, then hand-picked:
-- the diff also proposed several unrelated index renames/FK drop-recreates
-- on orders/refresh_tokens/auth_audit_logs (pre-existing naming drift
-- between this DB's hand-written migrations and Prisma's default naming
-- convention) — deliberately excluded, out of scope for this change.

-- AlterTable
ALTER TABLE "users" ADD COLUMN "reset_password_otp_last_sent_at" TIMESTAMPTZ(6);

-- DropForeignKey
ALTER TABLE "device_registrations" DROP CONSTRAINT "device_registrations_refresh_token_id_fkey";
ALTER TABLE "device_registrations" DROP CONSTRAINT "device_registrations_user_id_fkey";

-- DropTable
DROP TABLE "device_registrations";

-- CreateTable
CREATE TABLE "mobile_verifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "company_id" UUID NOT NULL,
    "mobile_number" TEXT NOT NULL,
    "otp_hash" TEXT NOT NULL,
    "otp_expires_at" TIMESTAMPTZ(6) NOT NULL,
    "otp_attempts" INTEGER NOT NULL DEFAULT 0,
    "last_sent_at" TIMESTAMPTZ(6) NOT NULL,
    "verified_at" TIMESTAMPTZ(6),
    "verification_token" TEXT,
    "token_expires_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mobile_verifications_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "mobile_verifications_verification_token_key" ON "mobile_verifications"("verification_token");

-- CreateIndex
CREATE UNIQUE INDEX "mobile_verifications_company_id_mobile_number_key" ON "mobile_verifications"("company_id", "mobile_number");

-- AddForeignKey
ALTER TABLE "mobile_verifications" ADD CONSTRAINT "mobile_verifications_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`.
-- ============================================================================

-- --- Non-superuser application role grant ------------------------------------
-- No DELETE — a row is superseded (upserted) on resend, never removed by
-- application code.
GRANT SELECT, INSERT, UPDATE ON "mobile_verifications" TO app_user;

-- --- Row Level Security ------------------------------------------------------
-- Every access to this table happens pre-authentication (send-verification,
-- verify-mobile, and registerStudent's own token lookup all run with no
-- real user session) — the same auth_service system-actor identity already
-- established for categories/departments pre-auth reads
-- (20260906150000_student_self_registration/migration.sql). No other
-- legitimate access path exists, so a single FOR ALL policy is sufficient
-- (mirroring payment_service_payment_attempts's own single-policy shape,
-- 20260906200000_payment_attempts/migration.sql).
ALTER TABLE "mobile_verifications" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth_service_mobile_verifications" ON "mobile_verifications"
  FOR ALL
  USING (current_setting('app.current_system_actor', true) = 'auth_service')
  WITH CHECK (current_setting('app.current_system_actor', true) = 'auth_service');
