-- CreateTable
CREATE TABLE "orders" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "company_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'order_placed',
    "items" JSONB NOT NULL,
    "total_amount" INTEGER NOT NULL,
    "otp" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "delivered_at" TIMESTAMPTZ(6),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "deliveries" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "order_id" UUID NOT NULL,
    "company_id" UUID NOT NULL,
    "delivered_by" UUID NOT NULL,
    "delivered_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_audit_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "order_id" UUID NOT NULL,
    "company_id" UUID NOT NULL,
    "event_type" TEXT NOT NULL,
    "performed_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "deliveries_order_id_key" ON "deliveries" ("order_id");

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_delivered_by_fkey" FOREIGN KEY ("delivered_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_audit_logs" ADD CONSTRAINT "order_audit_logs_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_audit_logs" ADD CONSTRAINT "order_audit_logs_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_audit_logs" ADD CONSTRAINT "order_audit_logs_performed_by_fkey" FOREIGN KEY ("performed_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. `orders` here is the minimal slice
-- specs/005-staff-order-fulfilment-otp's own data-model.md documents as a
-- "Dependency" (owned by a future Checkout & Payment feature, specs/006 —
-- not built yet); `deliveries`/`order_audit_logs` are fully owned by 005.
-- ============================================================================

-- The incoming-orders hot query: WHERE company_id = :x AND status = 'order_placed'.
CREATE INDEX "orders_company_id_status_idx" ON "orders" ("company_id", "status");

-- --- Non-superuser application role grants -----------------------------------
-- orders: no DELETE — never hard-deleted, and this feature only ever
-- transitions status/delivered_at, never removes a row.
GRANT SELECT, INSERT, UPDATE ON "orders" TO app_user;
-- deliveries: INSERT only beyond SELECT — created once, never updated
-- (FR-008's UNIQUE(order_id) is what actually prevents a second one).
GRANT SELECT, INSERT ON "deliveries" TO app_user;
-- order_audit_logs: append-only (data-model.md), same shape as auth_audit_logs.
GRANT SELECT, INSERT ON "order_audit_logs" TO app_user;

-- --- Row Level Security ------------------------------------------------------
-- data-model.md's own instruction: company_id-scoped, NO system_admin
-- bypass on any of the three tables — consistent with 004's Products
-- precedent of not granting cross-tenant access unless a spec explicitly
-- authorizes it (nothing here does).
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "deliveries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_audit_logs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "orders_tenant_isolation" ON "orders"
  FOR ALL
  USING ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid)
  WITH CHECK ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid);

CREATE POLICY "deliveries_tenant_isolation" ON "deliveries"
  FOR ALL
  USING ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid)
  WITH CHECK ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid);

CREATE POLICY "order_audit_logs_tenant_isolation" ON "order_audit_logs"
  FOR ALL
  USING ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid)
  WITH CHECK ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid);
