-- specs/016-feedback-management. New tenant-scoped `feedback` table — see
-- data-model.md §1 and research.md §1-§5.
--
-- Hand-written in full (not `prisma migrate dev --create-only` output) — no
-- live database is reachable from this environment. The CREATE TABLE below
-- is exactly what Prisma would have generated from the schema.prisma diff;
-- everything below the "HAND-ADDED" marker is, as always (coding_standard.md
-- §4.2), not expressible in schema.prisma at all.

-- CreateTable
CREATE TABLE "feedback" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "company_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "rating" SMALLINT,
    "category" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "contact_requested" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'new',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "feedback_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`.
-- ============================================================================

-- FR-002/FR-003/FR-004/FR-007/FR-009/FR-013 (data-model.md §1): enforced at
-- the DB layer, not only in application validation.
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_rating_range" CHECK ("rating" IS NULL OR "rating" BETWEEN 1 AND 5);
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_category_values" CHECK ("category" IN ('app_experience', 'food_order_quality', 'payment_issue', 'pickup_experience', 'suggestion', 'other'));
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_message_length" CHECK (char_length("message") BETWEEN 1 AND 1000);
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_status_values" CHECK ("status" IN ('new', 'resolved'));

-- The Company Admin review queue's primary query shapes (FR-010/FR-011 —
-- "this company's feedback, optionally filtered by status" / "newest
-- first").
CREATE INDEX "feedback_company_id_status_idx" ON "feedback" ("company_id", "status");
CREATE INDEX "feedback_company_id_created_at_idx" ON "feedback" ("company_id", "created_at" DESC);

-- --- Non-superuser application role grant ------------------------------------
-- No DELETE — this feature never hard-deletes a feedback record.
GRANT SELECT, INSERT, UPDATE ON "feedback" TO app_user;

-- --- Row Level Security ------------------------------------------------------
-- Single FOR ALL policy, matching the shape already used for
-- products/categories/departments/users elsewhere in this schema.
-- DELIBERATELY no system_admin bypass predicate (research.md/data-model.md
-- Row Level Security section — spec Assumptions: System Admin is excluded
-- from this feature entirely, unlike Categories/Departments/Companies/Roles).
-- Within a tenant, who may call which endpoint (any role may POST, only
-- company_admin may GET/PATCH the review surface) is enforced at the API/
-- authorization layer (@Roles(...)), not here — RLS only needs to answer
-- "which company."
ALTER TABLE "feedback" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "feedback_tenant_isolation" ON "feedback"
  FOR ALL
  USING ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid)
  WITH CHECK ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid);

-- --- Audit trigger (research.md §2) ------------------------------------------
-- Reuses the existing, already-generic fn_audit_log() from
-- 20260906210000_audit_logs unmodified — every table other than
-- payment_attempts (which has no company_id of its own) falls through to
-- `v_company_id := NEW.company_id`, exactly feedback's shape. The
-- products-only 'removed' branch in that function is additive and simply
-- doesn't fire here; a feedback.is_deleted transition (not exercised by any
-- endpoint in this feature) would log as a generic 'updated' action, which
-- is harmless and consistent with how orders/payment_attempts are already
-- handled.
CREATE TRIGGER audit_feedback
  AFTER INSERT OR UPDATE ON "feedback"
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
