-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "issued_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "revoked_at" TIMESTAMPTZ(6),
    "replaced_by" UUID,
    "user_agent" TEXT,
    "ip_address" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auth_audit_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID,
    "company_id" UUID,
    "event_type" TEXT NOT NULL,
    "refresh_token_id" UUID,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens" ("token_hash");

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_replaced_by_fkey" FOREIGN KEY ("replaced_by") REFERENCES "refresh_tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "auth_audit_logs" ADD CONSTRAINT "auth_audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "auth_audit_logs" ADD CONSTRAINT "auth_audit_logs_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "auth_audit_logs" ADD CONSTRAINT "auth_audit_logs_refresh_token_id_fkey" FOREIGN KEY ("refresh_token_id") REFERENCES "refresh_tokens"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. specs/002-registration-login-jwt-auth's data-model.md
-- requirements that Prisma's schema DSL cannot express live here: unique/
-- composite indexes, RLS policies, and GRANTs. Do NOT regenerate this
-- migration from schema.prisma alone — everything below would be lost.
-- ============================================================================

-- --- Indexes (data-model.md §1) ---------------------------------------------
-- (the token_hash unique index itself is Prisma-native — see the
-- Prisma-generated CreateIndex block above, not hand-added here)

-- The hot lookup path for "does this user have any active sessions to
-- revoke" (lock, deactivation, password change) and "list a user's active
-- sessions."
CREATE INDEX "refresh_tokens_user_id_revoked_at_idx" ON "refresh_tokens" ("user_id", "revoked_at");

-- auth_audit_logs is written far more than it's read; index the two shapes
-- a future viewing feature (or this feature's own tests) would query by.
CREATE INDEX "auth_audit_logs_user_id_created_at_idx" ON "auth_audit_logs" ("user_id", "created_at");
CREATE INDEX "auth_audit_logs_company_id_created_at_idx" ON "auth_audit_logs" ("company_id", "created_at");

-- --- Non-superuser application role grants ----------------------------------
-- app_user (created by 001's migration) needs read/write on both new tables.
-- No DELETE is granted anywhere — neither table has an application-facing
-- delete path (refresh_tokens rows are revoked via UPDATE, never removed;
-- auth_audit_logs is append-only, per data-model.md).
GRANT SELECT, INSERT, UPDATE ON "refresh_tokens" TO app_user;
GRANT SELECT, INSERT ON "auth_audit_logs" TO app_user; -- INSERT only, never UPDATE/DELETE — append-only (FR-018)

-- --- Row Level Security ------------------------------------------------------

ALTER TABLE "refresh_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auth_audit_logs" ENABLE ROW LEVEL SECURITY;

-- refresh_tokens: a user can only see/revoke their own tokens; System Admin
-- has the platform-wide bypass already established for every other table
-- (001 precedent). A THIRD disjunct, app.current_system_actor = 'auth_service',
-- exists specifically for the one pre-authentication lookup this feature's
-- own login/refresh flows require: at the moment /auth/refresh receives a raw
-- token, the backend does not yet know which user_id it belongs to (that's
-- the very thing the lookup is determining) and therefore cannot set
-- app.current_user_id before running it. This mirrors the exact pattern
-- coding_standard.md §4.3 documents for `006`'s payment-webhook handler: a
-- narrowly-scoped, code-path-specific service identity, not a general RLS
-- bypass available to any application code. Once the row is found, every
-- subsequent write in the same request (rotation, revocation) runs under the
-- FOUND user's own real {userId, role, companyId} context instead, per
-- coding_standard.md's "no bypass unless a spec's FRs explicitly grant it"
-- rule — the system_actor disjunct is used for this one SELECT shape only.
CREATE POLICY "refresh_tokens_self_or_system" ON "refresh_tokens"
  FOR ALL
  USING (
    "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  )
  WITH CHECK (
    "user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  );

-- auth_audit_logs: split into a read policy (company-scoped, for a future
-- Company Admin / System Admin viewing feature — not built by this feature,
-- but the RLS shape already supports it per data-model.md's own prose) and a
-- write policy (backend-service-only — this table has no end-user-facing
-- write path at all; every row is inserted by AuthAuditService, including
-- for a login attempt against a username that never resolved to any account,
-- where no user_id/company_id exists yet to scope a "self" predicate against).
-- Also allows the auth_service system-actor to read back a row it just
-- wrote: Postgres RLS evaluates a table's SELECT policy against an
-- INSERT ... RETURNING row too (RETURNING a row is itself a form of read) —
-- Prisma's .create() always uses RETURNING, so without this disjunct every
-- AuthAuditService write would fail despite its own INSERT WITH CHECK
-- passing (discovered while implementing this migration, not by design).
CREATE POLICY "auth_audit_logs_select" ON "auth_audit_logs"
  FOR SELECT
  USING (
    current_setting('app.current_role', true) = 'system_admin'
    OR (
      current_setting('app.current_role', true) = 'company_admin'
      AND "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    )
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  );

CREATE POLICY "auth_audit_logs_insert" ON "auth_audit_logs"
  FOR INSERT
  WITH CHECK (current_setting('app.current_system_actor', true) = 'auth_service');

-- --- Widen 001's existing `users` policy with the same auth_service bypass -
-- 001's users_tenant_isolation policy has no predicate that lets an
-- unauthenticated request read a `users` row at all — by definition, no JWT
-- (and therefore no app.current_user_id/role/company_id) exists yet at the
-- moment /auth/login needs to look a username up. This is the exact same
-- "pre-authentication lookup" need refresh_tokens_self_or_system above
-- exists for, and gets the identical, narrowly-scoped fix: one additional
-- disjunct, reusing the same auth_service system-actor identity, added via
-- an additive DROP+CREATE in this feature's own migration rather than
-- editing 001's already-created migration file (coding_standard.md §4.2's
-- "never regenerate/rewrite a prior migration" discipline). Once a row is
-- found, every subsequent read/write in the same login flow switches to
-- that row's own real {user_id, role, company_id} — this bypass is used for
-- the initial identity-unknown SELECT only, never as a general escape hatch.
DROP POLICY "users_tenant_isolation" ON "users";
CREATE POLICY "users_tenant_isolation" ON "users"
  FOR ALL
  USING (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  )
  WITH CHECK (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  );

-- 001's `roles_select` policy needs the identical widening: AuthService's
-- pre-auth lookups join `users` to `roles` (Prisma `include: { role: true }`)
-- to resolve the found account's role name — a nested SELECT against
-- `roles` that RLS evaluates independently of the outer `users` query, and
-- that join returns nothing (silently producing a null relation, not an
-- error, until Prisma itself complains the required relation is missing)
-- for a company-scoped role under the pre-auth context, which has no
-- app.current_company_id set yet. Discovered running this feature's own
-- test suite against a real database, not by design up front.
DROP POLICY "roles_select" ON "roles";
CREATE POLICY "roles_select" ON "roles"
  FOR SELECT
  USING (
    current_setting('app.current_role', true) = 'system_admin'
    OR "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_system_actor', true) = 'auth_service'
  );
