-- CreateTable
CREATE TABLE "companies" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "contact_person" TEXT NOT NULL,
    "mobile" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "is_open" BOOLEAN NOT NULL DEFAULT true,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "companies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roles" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "company_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "categories" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "company_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "departments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "company_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "departments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "company_id" UUID,
    "role_id" UUID NOT NULL,
    "category_id" UUID,
    "department_id" UUID,
    "name" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "no_of_login_attempt" INTEGER NOT NULL DEFAULT 0,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "roles" ADD CONSTRAINT "roles_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "categories" ADD CONSTRAINT "categories_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "departments" ADD CONSTRAINT "departments_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. This is where specs/001-company-role-user-setup's
-- data-model.md requirements that Prisma's schema DSL cannot express live:
-- partial unique indexes, CHECK constraints, the role-seeding trigger, RLS
-- policies, and the non-superuser application role. Do NOT regenerate this
-- migration from schema.prisma alone — everything below would be lost.
-- ============================================================================

-- --- Partial unique indexes (data-model.md §2-§5) ---------------------------

-- roles: a company cannot have two roles with the same name; the single
-- global system_admin role (company_id IS NULL) is unique on its own.
CREATE UNIQUE INDEX "roles_company_name_unique" ON "roles" ("company_id", "name") WHERE "company_id" IS NOT NULL;
CREATE UNIQUE INDEX "roles_global_system_admin_unique" ON "roles" ("name") WHERE "company_id" IS NULL;

-- categories / departments: case-insensitive uniqueness per company among
-- non-removed rows only (a removed name can be reused).
CREATE UNIQUE INDEX "categories_company_name_unique" ON "categories" ("company_id", lower("name")) WHERE "is_deleted" = false;
CREATE UNIQUE INDEX "departments_company_name_unique" ON "departments" ("company_id", lower("name")) WHERE "is_deleted" = false;

-- users: username unique per company among non-removed rows; a separate
-- index covers the global system_admin case (company_id IS NULL), since a
-- composite index does not treat two NULLs as equal to begin with — this
-- second index exists for clarity of intent, matching data-model.md §5.
CREATE UNIQUE INDEX "users_company_username_unique" ON "users" ("company_id", lower("username")) WHERE "is_deleted" = false AND "company_id" IS NOT NULL;
CREATE UNIQUE INDEX "users_global_username_unique" ON "users" (lower("username")) WHERE "is_deleted" = false AND "company_id" IS NULL;

-- --- CHECK constraints (data-model.md §2) -----------------------------------
-- Only the constraint expressible without a cross-table lookup is a real DB
-- CHECK. The role/company/category consistency rules in data-model.md §5
-- reference other tables (a role's own name) and are enforced at the
-- application layer, as data-model.md itself specifies — not duplicated here
-- as an unenforceable CHECK.
ALTER TABLE "roles" ADD CONSTRAINT "roles_company_id_or_system_admin" CHECK ("company_id" IS NOT NULL OR "name" = 'system_admin');

-- --- Role-seeding trigger (data-model.md §1, research.md §3) ----------------
-- SECURITY DEFINER + owned by the migration role so it can always insert
-- into `roles` regardless of what is granted to the application's own
-- database role (app_user, created below) — the application role is
-- deliberately never granted INSERT on `roles` at all (see GRANTs below).
CREATE OR REPLACE FUNCTION fn_seed_company_roles()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO "roles" ("id", "name", "company_id", "created_at", "updated_at")
  VALUES
    (gen_random_uuid(), 'SYSTEM_ADMIN', NEW."id", now(), now()),
    (gen_random_uuid(), 'COMPANY_ADMIN', NEW."id", now(), now()),
    (gen_random_uuid(), 'STAFF', NEW."id", now(), now()),
    (gen_random_uuid(), 'STUDENT', NEW."id", now(), now()),
    (gen_random_uuid(), 'TEACHING', NEW."id", now(), now()),
    (gen_random_uuid(), 'NON_TEACHING', NEW."id", now(), now());
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_seed_company_roles
  AFTER INSERT ON "companies"
  FOR EACH ROW
  EXECUTE FUNCTION fn_seed_company_roles();

-- --- Non-superuser application role -----------------------------------------
-- The Node API connects as this role, never as the migration/table-owning
-- role — RLS below is meaningless against a superuser or the table owner,
-- both of which bypass it entirely (coding_standard.md §5, BRD §9).
-- Deliberately created WITHOUT a password. A committed migration file must
-- never contain a real, working credential (coding_standard.md §10) — even
-- a randomly-generated one is still a real secret once it's the one that
-- actually authenticates against a live database. The password is set in a
-- SEPARATE, not-version-controlled step: run
-- `scripts/set-app-user-password.sh` (reads from an env var, never a
-- literal) once per environment after this migration applies. Until that
-- runs, `app_user` exists but cannot authenticate via password.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user LOGIN;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE ON "companies" TO app_user;
GRANT SELECT ON "roles" TO app_user; -- INSERT/UPDATE intentionally NOT granted — only fn_seed_company_roles (SECURITY DEFINER) may write
GRANT SELECT, INSERT, UPDATE ON "categories" TO app_user;
GRANT SELECT, INSERT, UPDATE ON "departments" TO app_user;
GRANT SELECT, INSERT, UPDATE ON "users" TO app_user;

-- --- Row Level Security (data-model.md "Row Level Security Summary") -------

ALTER TABLE "companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "departments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;

-- companies: System Admin only — company management is System-Admin-only
-- per FR-001/FR-002; no other role sees a company row directly through this
-- table (they learn their own company's identity from their JWT, not a row
-- read here).
CREATE POLICY "companies_system_admin_only" ON "companies"
  FOR ALL
  USING (current_setting('app.current_role', true) = 'system_admin')
  WITH CHECK (current_setting('app.current_role', true) = 'system_admin');

-- roles: readable platform-wide by system_admin, readable (not writable) by
-- any authenticated user scoped to their own company_id. No INSERT/UPDATE
-- policy exists for any role — the only writer is the SECURITY DEFINER
-- trigger function above, which bypasses RLS as the table owner.
CREATE POLICY "roles_select" ON "roles"
  FOR SELECT
  USING (
    current_setting('app.current_role', true) = 'system_admin'
    OR "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
  );

-- categories / departments / users: company-scoped read/write, with a
-- system_admin bypass for full cross-tenant CRUD (FR-005/FR-021).
CREATE POLICY "categories_tenant_isolation" ON "categories"
  FOR ALL
  USING (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
  )
  WITH CHECK (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
  );

CREATE POLICY "departments_tenant_isolation" ON "departments"
  FOR ALL
  USING (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
  )
  WITH CHECK (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
  );

CREATE POLICY "users_tenant_isolation" ON "users"
  FOR ALL
  USING (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
  )
  WITH CHECK (
    "company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid
    OR current_setting('app.current_role', true) = 'system_admin'
  );
