-- CreateTable
CREATE TABLE "products" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "company_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "image_url" TEXT,
    "price" INTEGER NOT NULL,
    "is_veg" BOOLEAN NOT NULL,
    "is_soldout" BOOLEAN NOT NULL DEFAULT false,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`. specs/004-company-admin-product-crud data-model.md's
-- own requirements that Prisma's schema DSL cannot express: the price CHECK
-- constraint, the hot list-query index, RLS, and the app_user GRANT.
-- ============================================================================

-- FR-004/FR-010: enforced at the DB layer, not only in application validation.
ALTER TABLE "products" ADD CONSTRAINT "products_price_positive" CHECK ("price" > 0);

-- The list-all-active-products-for-my-company query (FR-010) is the hot path.
CREATE INDEX "products_company_id_is_deleted_idx" ON "products" ("company_id", "is_deleted");

-- --- Non-superuser application role grant ------------------------------------
-- No DELETE — this feature never hard-deletes a product (FR-008/FR-009).
GRANT SELECT, INSERT, UPDATE ON "products" TO app_user;

-- --- Row Level Security ------------------------------------------------------
-- data-model.md's own RLS section: company_id-scoped, and DELIBERATELY no
-- system_admin bypass predicate (FR-003 as corrected during planning — this
-- spec grants System Admin no cross-tenant Product access, unlike every
-- other tenant-scoped table in this schema). A single FOR ALL policy is used
-- here (rather than data-model.md's illustrative separate SELECT/write
-- policies) since both predicates are identical — this matches the single-
-- FOR-ALL-policy shape already used for categories/departments/users
-- elsewhere in this schema, with no behavioral difference.
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "products_tenant_isolation" ON "products"
  FOR ALL
  USING ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid)
  WITH CHECK ("company_id" = NULLIF(current_setting('app.current_company_id', true), '')::uuid);
