-- specs/011-audit-logs-product-order-payment. Builds the generic
-- "every mutation of a business-critical table is recorded in audit_logs
-- automatically via database triggers" mechanism that Architecture §7/§10
-- and BRD Assumption 8 have referenced since 001 but never designed.
-- Scoped exactly to products (004), orders (006), and payment_attempts
-- (010) per this feature's own explicit scope note — not Companies, Roles,
-- Categories, Departments, or Users.

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "table_name" TEXT NOT NULL,
    "record_id" UUID NOT NULL,
    "company_id" UUID,
    "action" TEXT NOT NULL,
    "changed_fields" JSONB,
    "performed_by_user_id" UUID,
    "performed_by_system" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_performed_by_user_id_fkey" FOREIGN KEY ("performed_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- HAND-ADDED BELOW THIS LINE (coding_standard.md §4.2) — not generated by
-- `prisma migrate dev`.
-- ============================================================================

-- data-model.md §1: exactly one actor identity is always present, never
-- both, never neither (FR-005, SC-004) — this is the mechanism, not just a
-- convention: a write path that forgets to set either session variable
-- fails loudly here rather than producing a blank-actor row.
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_exactly_one_actor" CHECK (("performed_by_user_id" IS NOT NULL) <> ("performed_by_system" IS NOT NULL));

-- The natural "full history of this one record" query shape a future
-- viewing feature would use (data-model.md §1).
CREATE INDEX "audit_logs_table_record_created_idx" ON "audit_logs" ("table_name", "record_id", "created_at");

-- --- Immutability at the database layer (research.md §5, FR-006) -----------
-- No GRANT of any kind to app_user on this table: the deny-by-default
-- posture means the application's own DB role starts with zero privileges
-- here (no SELECT either — research.md §6, "no application-facing read path
-- exists in this feature"). The explicit REVOKE below is a belt-and-suspenders
-- guard against a future accidental broad GRANT (e.g. a careless
-- `GRANT ALL ... ON ALL TABLES`) ever re-opening UPDATE/DELETE here — a bug
-- or a future feature that *tries* to alter an audit row must fail loudly
-- at the database, never silently succeed.
REVOKE UPDATE, DELETE ON "audit_logs" FROM app_user;

-- --- Row Level Security ------------------------------------------------------
-- Enabled with NO SELECT policy for any application role — matches this
-- feature's explicit "capture only, no viewing screen" scope (research.md
-- §6). Only a direct database-admin connection (outside app_user) can read
-- this table today; a future viewing feature adds a policy, it doesn't need
-- to retrofit tenant scoping onto previously-unscoped data.
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;

-- --- Generic trigger function (research.md §1-§4) ---------------------------
-- SECURITY DEFINER + owned by the migration role, mirroring
-- fn_seed_company_roles' own established pattern (001's migration) — so it
-- can always insert into audit_logs regardless of what's granted to
-- app_user above (deliberately nothing), and so its INSERT bypasses RLS as
-- the table owner rather than needing its own policy.
--
-- Table-agnostic by design (research.md §1): attached identically to
-- products, orders, and payment_attempts. Field access on OLD/NEW that is
-- only valid for one specific table (products.is_deleted, orders.company_id
-- vs payment_attempts.order_id) is always guarded by a TG_TABLE_NAME check
-- in the SAME boolean expression or a separate IF/ELSE branch, relying on
-- Postgres's short-circuit evaluation of AND/OR — never evaluated for a
-- table where the field wouldn't exist.
CREATE OR REPLACE FUNCTION fn_audit_log()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_action text;
  v_company_id uuid;
  v_changed jsonb := '{}'::jsonb;
  v_old jsonb;
  v_new jsonb;
  v_key text;
  v_user_id text;
  v_system_actor text;
  v_excluded text[] := ARRAY['created_at', 'updated_at', 'created_by', 'updated_by'];
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_action := 'created';
  ELSE
    -- research.md §2: an UPDATE is 'removed' only for products' own
    -- soft-delete transition; every other UPDATE (on any of the three
    -- tables) is 'updated'. orders/payment_attempts have no is_deleted
    -- column at all and are never soft-deleted.
    IF TG_TABLE_NAME = 'products' AND (OLD.is_deleted IS DISTINCT FROM NEW.is_deleted) AND NEW.is_deleted = true THEN
      v_action := 'removed';
    ELSE
      v_action := 'updated';
    END IF;

    -- research.md §3: diff OLD/NEW, excluding bookkeeping columns that
    -- trivially change on every write and carry no business meaning.
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    FOR v_key IN SELECT jsonb_object_keys(v_new) LOOP
      IF v_key = ANY(v_excluded) THEN
        CONTINUE;
      END IF;
      IF v_old -> v_key IS DISTINCT FROM v_new -> v_key THEN
        v_changed := v_changed || jsonb_build_object(v_key, jsonb_build_object('old', v_old -> v_key, 'new', v_new -> v_key));
      END IF;
    END LOOP;
  END IF;

  -- research.md §6: company_id is direct for products/orders, resolved via
  -- a join to the owning order for payment_attempts (which has no
  -- company_id column of its own, per 010).
  IF TG_TABLE_NAME = 'payment_attempts' THEN
    SELECT o."company_id" INTO v_company_id FROM "orders" o WHERE o."id" = NEW."order_id";
  ELSE
    v_company_id := NEW."company_id";
  END IF;

  -- research.md §4: read whichever session variable the caller set —
  -- TenantPrismaService.runInTenantContext always sets both (one to a real
  -- value, the other to ''), so NULLIF collapses the unset one to NULL.
  -- Neither set (empty string on both) → both columns NULL → rejected by
  -- audit_logs_exactly_one_actor, i.e. the write fails loudly rather than
  -- producing a blank-actor row (plan.md's explicit "fail loud" choice).
  v_user_id := NULLIF(current_setting('app.current_user_id', true), '');
  v_system_actor := NULLIF(current_setting('app.current_system_actor', true), '');

  INSERT INTO "audit_logs" (
    "id", "table_name", "record_id", "company_id", "action", "changed_fields",
    "performed_by_user_id", "performed_by_system", "created_at"
  ) VALUES (
    gen_random_uuid(),
    TG_TABLE_NAME,
    NEW."id",
    v_company_id,
    v_action,
    CASE WHEN TG_OP = 'INSERT' THEN NULL WHEN v_changed = '{}'::jsonb THEN NULL ELSE v_changed END,
    v_user_id::uuid,
    v_system_actor,
    now()
  );

  RETURN NEW;
END;
$$;

-- --- Trigger attachment (data-model.md §2) ----------------------------------
CREATE TRIGGER audit_products
  AFTER INSERT OR UPDATE ON "products"
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

CREATE TRIGGER audit_orders
  AFTER INSERT OR UPDATE ON "orders"
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

CREATE TRIGGER audit_payment_attempts
  AFTER INSERT OR UPDATE ON "payment_attempts"
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();
